server:
  port: 80

   #context-path: /mass
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project_appraisal?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #mvc:
    #static-path-pattern: /**
  #resources:
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/itstyle/
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 100Mb

mybatis:
  config-location: classpath:/mybatis-config.xml
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mapper-locations: classpath:mapping/*Mapper.xml
type-aliases-package: com.example.entity

#showSql
#logging:
  #level:
    #com:
     # example:
       # mapper : debug